### ISSUE TITLE
Fast food and is this a bookstore are showing up for Barnes & Noble in error

### ISSUE THREAD

**Issue by t0cableguy** [WazeDev/WME-Place-Harmonizer#110]
https://www.waze.com/editor/?env=usa&lon=-87.85319&lat=42.69990&zoom=5&mode=0&venues=178323883.1783500974.2090382

Personally observed fast food, and is this a bookstore (with bookstore in the categories!!!) questions for barnes & noble.
dmee92 reports seeing is there a "supermarket/grocery"

**Comment by t0cableguy** [comment]
Sent: 2017-01-28, 8:58 pm
by dmee92
Script version: 1.1.93Beta
Permalink: https://www.waze.com/editor/?env=usa&lo ... 74.2090382
Place name: Barnes & Noble
Country: United States
--------
Describe the error: In the production version it would ask multiple times if it was a BOOKSTORE even after pressing YES. However, now in the BETA is is asking if there is a SUPERMARKET_GROCERY at this location.

**Comment by mapomatic** [comment]
This was fixed at some point and now correctly asks if there is a Coffee Shop at that location.  However, clicking the button just throws an error, so I'll open a new issue.
