### ISSUE TITLE
Wont run on a place without a state name.

### ISSUE THREAD

**Issue by t0cableguy** [WazeDev/WME-Place-Harmonizer#15]
note from readme. **Note that for some app-submitted places, no state name is stored.  In these cases, you have to enter at least a city and street in the address field for the script to run.

It would be ideal to fix this issue. however this has been an issue for a long time.

**Comment by t0cableguy** [comment]
This is a middle of the road bug. It doesn't cause wmeph to hang, however wmeph will not do anything with places like this. We need to find some examples so we can test fixes on places with this issue. We've also been coping with it for a long time so I'd consider it a low priority bug. 

Please don't invest a lot of time in this unless you know of an easy fix.

**Comment by mapomatic** [comment]
Determined that in the example PL, there are no streets nearby for the script to infer an address from.  Streets are the only objects in the Waze data model that actually have a reference to a city/state.  One idea is to use an external call to a Google function that would return state (same one used in WME GIS).  Would still somehow need to add a city (or No City) and street (or No Street) for the rest of the script to work.  Worst case, we leave it as is and the user has to manually enter the info in these cases.  I assume they're rare... (?)

**Comment by helifino** [comment]
Note, Toolbox currently can auto-set a street's city/state based on the black bar bounding box, so the data is there somewhere already.

**Comment by RavenDT** [comment]
I'm still puzzled on how that place can't even have a state in it.  Why does the map not even show the state?  It just says in the grey part, "United States".

**Comment by RavenDT** [comment]
We have a case for "No HN" and "No Street", I'm not sure about "No City", we should just add cases for "No State" and "No Country".

It would be cool if we could find a way to remove all other cases if "No Country" is true, so literally, the only thing you can do after you run the script is be prompted for a Country.  ;)

**Comment by helifino** [comment]
TB's "prefill" still manages to pull the state name (and properly sets the city to 'none') even though it doesn't appear on the bar.

**Comment by jangliss** [comment]
`W.model.state` will have state data based on items that are in the area cache.  For example on that cemetery it has Florida.  This might be a _good enough_ type of fix.  The same can be used for Cities as well, but that's more likely to cause issues, especially in high density city areas.

**Comment by Clete2** [comment]
Also happens when country is deemed as blank.

        var countryName = addr.country.name;


Easy fix

**Comment by mapomatic** [comment]
I think I've got it fixed up now, so cases where there are no state/country set (and they can't be inferred) should display a popup asking the user to edit the address first.  #318
