### ISSUE TITLE
Hotel Services

### ISSUE THREAD

**Issue by jm6087** [WazeDev/WME-Place-Harmonizer#212]
I would like to suggest that WMEPH automatically adds the following services to hotels

Wifi
Parking
24/7

**Comment by mapomatic** [comment]
Mods decided that 24/7 should be applied to all hotels.  Wifi should go on hotels if they match PNH.  No user message is necessary.

If hotel is not in PNH, show the Wifi service button in the banner (but don't turn on automatically).

**Comment by mapomatic** [comment]
Addressed in v1.3.13
