### ISSUE TITLE
Check hours for same open/close times.  Bug?

### ISSUE THREAD

**Issue by turbomkt** [WazeDev/WME-Place-Harmonizer#31]
Waze has a save error when a place has the same open and close times set (e.g. 9a-9a).  This was not generated by WMEPH, but it would be nice if it checked for the issue.

**Comment by t0cableguy** [comment]
the code exists in the script that is supposed to flag this, however I guess it has stopped working. 
I wouldn't consider this a major bug, but it does need to get fixed.

**Comment by mapomatic** [comment]
Maybe not ideal, but the next release will show the "Can't parse" message if open/close times are the same.  Adding a custom message would take some more effort.
