### ISSUE TITLE
Hours should ignore timezone

### ISSUE THREAD

**Issue by Clete2** [WazeDev/WME-Place-Harmonizer#312]
WMEPH fails to parse the below string:
```
Mon-Sat 10:00am - 9:00pm (EST)
Sun 12:00pm - 7:00pm (EST)
```

**Comment by Clete2** [comment]
Opened PR #313 to fix this.

Original page that caused me the issue: https://www.belk.com/store/?StoreID=337

**Comment by mapomatic** [comment]
Thanks for the report.  After implementing your fix in the HoursParser library in the WME Utils repo, this issue should now be fixed.
