### ISSUE TITLE
Idea: Add field to insert entire address, then parse into separate fields.

### ISSUE THREAD

**Issue by RavenDT** [WazeDev/WME-Place-Harmonizer#33]
Idea: Add field to insert entire address, then parse into separate fields.

Example: Place has an inferred city, incorrect street, no house number.
Copy and paste entire correct address in:

Add address: [ 123 Correct St., Americaland, US ]

It parses and overwrites the incorrect data.

**Comment by t0cableguy** [comment]
Sounds like a great Idea.

**Comment by t0cableguy** [comment]
Mark (well a couple people) had an idea at one time to make a single text input box that could guess what is in it. And we could have a couple buttons to force it to send the info to one spot or the other. This would reduce the space needed to show the script st the top of the info pane.

**Comment by RavenDT** [comment]
It could be possible, but I don't know if that'd be the best idea.  WMEPH has a bullet list of everything it finds wrong (or actions it takes like locking), and if we combine fields, it might get convoluted and/or confusing.

As far as reducing the space, I was considering submitting an issue (enhancement) of seeing about altering the styles to make the fields and/or text slightly smaller.  When you enable features like the copy/paste address stuff, it takes up a lot of room and there's a lot of scrolling up and down.

Even if we don't reduce the size of the styles, as long as the address field (and/or URL field) go away like the phone number field after you add something, it/they shouldn't be too cumbersome.

**Comment by StormeHawke** [comment]
> It could be possible, but I don't know if that'd be the best idea. WMEPH has a bullet list of everything it finds wrong (or actions it takes like locking), and if we combine fields, it might get convoluted and/or confusing.

I think it could be dynamic - if just the street is missing, then it is a street input. IF only the HN is missing, then an HN input.  If both (or the entire address) are missing, then it could attempt to parse out the whole address.  There are some non-standard address cases that would need to be handled (Suite #s come to mind). The field wouldn't necessarily correspond 1-1 with the bullet list, but that's ok - Good UIs are user focused, and the logic would be doable

**Comment by RavenDT** [comment]
I like the idea of, "if one is missing, ask for the one item". The script already checks and responds if there is no HN or no street.  All we'd have to do is add a field for adding the street.

**Comment by mapomatic** [comment]
There are professional (not free) libraries that have compiled massive databases and heuristics to attempt to tackle the problem of robustly parsing addresses.  I don't think we want to go down this road.  I'm going to close this for now.
