### ISSUE TITLE
Enmark to Enmarket - Discord WMEPH Request

### ISSUE THREAD

**Issue by jm6087** [WazeDev/WME-Place-Harmonizer#351]
Posting this from Discord server so it don't get to lost.

Ref:  Order 1155   Approved by SER and SAT

![image](https://user-images.githubusercontent.com/24948653/49872020-6b9f4580-fddd-11e8-8e4e-6dbaad805dbc.png)

**Comment by mapomatic** [comment]
I believe this is working already?  Can you confirm @jm6087 and go ahead close this if so?

**Comment by jm6087** [comment]
You are correct.  According to discussions after I posted this, you have it working already.

Thamks
