### ISSUE TITLE
"Google" button doesn't properly encode all characters.

### ISSUE THREAD

**Issue by jangliss** [WazeDev/WME-Place-Harmonizer#355]
When a place name, or address, has a special character, it is not properly encoded when passed through to Google.  For example "Descargue NGL #3" with the address "RM 652, Orla, Texas" [PL](https://www.waze.com/en-US/editor/?env=usa&lon=-103.90418&lat=31.82756&zoom=7&venues=167838014.1678380143.6230140).  # is an anchor in HTML, referencing specific parts in a page, so is it be treated as a special character when passed as a query string element.  This example gets encoded as "Descargue%20NGL%20#3,%20RM%20652,%20Orla,%20Texas", which Google treats as stopping at the # resulting in the search only looking for Descargue NGL.  When properly encoded, it should be "Descargue%20NGL%20%233%2C%20RM%20652%2C%20Orla%2C%20Texas"

**Comment by justins83** [comment]
@jangliss This issue is resolved via your PR, correct?

**Comment by jangliss** [comment]
That is correct.  Not sure why this didn't get closed out, must have missed it when the merge got done.
