### ISSUE TITLE
Cici's Pizza

### ISSUE THREAD

**Issue by jm6087** [WazeDev/WME-Place-Harmonizer#360]
The PNH sheet (Order number 728) has Cicis listed as Primary and Cici's Pizza as Alt.

If someone enters Cici's Pizza as the primary and Cicis as the Alt, when WMEPH is run it puts Cicis in the primary, leaves Cicis as an Alt and does not put Cici's Pizza as an alt.

![image](https://user-images.githubusercontent.com/24948653/50864241-fa649b00-1366-11e9-9172-379257077b24.png)

Any other combination tested resulted in primary of Cicis and alt of Cici's Pizza as per PNH.

Tested the following that worked

Primary - Cicis (or Cici's)
Alt - Blank

Primary - Cici's Pizza
Alt - Blank

Primary - Cicis
Alt - Cici's Pizza

**Comment by mapomatic** [comment]
Maybe also related?  #344

**Comment by mapomatic** [comment]
Fixed in v1.3.136
