### ISSUE TITLE
Add Google Link Hangs Up

### ISSUE THREAD

**Issue by willdanneriv** [WazeDev/WME-Place-Harmonizer#379]
Adding Google Link button is throwing an error and showing just spinning circle.

![image](https://user-images.githubusercontent.com/5582060/58195427-f0986000-7c95-11e9-9bf8-9ce90756da30.png)

Example place that's exhibiting the error, but all places are having this issue for me. Tried on two different machines. 
https://www.waze.com/en-US/editor?env=usa&lon=-81.28775&lat=28.46669&zoom=6&venues=182649117.1826556703.2458825

**Comment by mapomatic** [comment]
This was determined to be an issue in native WME, not related to scripts.  Reported in the WME Beta Bugs forum.
