### ISSUE TITLE
SUGGESTION - Auto Run Feature

### ISSUE THREAD

**Issue by jm6087** [WazeDev/WME-Place-Harmonizer#382]
I would like to propose that (if possible), the option to "Auto Run WMEPH on selecting a place" is set to its default status of unchecked every time a new WME browser window is opened.   This is not a feature that should be run 100% of the time while using WMEPH as it causes more problems than it helps with.

**Comment by mapomatic** [comment]
I've actually completely removed the feature in an update I'm working (to be released soon).  It causes more problems than it solves.

**Comment by mapomatic** [comment]
The auto run feature was removed in the latest Beta, but I'll be working toward something that I hope will be better in the long-run.
