### ISSUE TITLE
Auto locking stopped working

### ISSUE THREAD

**Issue by jellicle0** [WazeDev/WME-Place-Harmonizer#387]
I'm guessing it happened with the latest WME update, but places still give the dashed circle when they need to be locked higher, but clicking on them no longer increases the lock level as it used to.  I don't know where it pulls the lock information from and if it's specific to some states/regions but it's failing in both UT and FL.

**Comment by jellicle0** [comment]
I'd tested on so many places and wasn't working.  Of course, as soon as I write it up, and test one more time, it works.

**Comment by mapomatic** [comment]
No worries.  Let me know if you run into it again.
