### ISSUE TITLE
Highlighting Fails at zoom 20 and more

### ISSUE THREAD

**Issue by eric215** [WazeDev/WME-Place-Harmonizer#411]
WMEPH Version 2021.08.05.001

Nothing else running.  At zoom levels 20 and more (zoomed in closer) the highlighting goes away

![image](https://user-images.githubusercontent.com/13973937/158225408-1d833e63-ce9b-4e51-82f2-d0c017efdc99.png)

![image](https://user-images.githubusercontent.com/13973937/158225468-df2b0ba6-29ea-475c-b6c7-931f7bad192b.png)

Eric
Ehcool68

**Comment by mapomatic** [comment]
This appears to have been fixed somewhere along the way.
