### ISSUE TITLE
Hours not parsing correctly in some cases where Sunday listed first

### ISSUE THREAD

**Issue by mapomatic** [WazeDev/WME-Place-Harmonizer#424]
When I paste hours that have Sunday listed first, the Sunday hours are left off the place. For example:
_Sunday & Monday: 11 am - 9 pm Tuesday - Saturday: 11 am - 10 pm_

It also doesn't work if Sunday is the only day and it's listed first, with the same hours as the following day, e.g.
_Sunday: 11 am - 9 pm Monday: 11 am - 9 pm Tuesday - Saturday: 11 am - 10 pm_

But this DOES work (different hours):
_Sunday: 11 am - 8 pm Monday: 11 am - 9 pm Tuesday - Saturday: 11 am - 10 pm_

**Comment by jm6087** [comment]
From my testing, it appears to only happen when Sunday and Monday are the same hours and the rest of the week is different.   If any other day has the same hours as Sunday and Monday, then it will parse correctly.

I tested the following

> _Sun 9am to 10pm, Mon 9am to 10pm, Tue 8am to 10pm, Wed 8am to 10pm, Thu 8am to 10pm_
> **Parses as** 
> _Mon 09:00-22:00
> Tue- Thu 08:00-22:00_

> _Sun 9am to 10pm, Mon 9am to 10pm, Tue 9am to 10pm, Wed 8am to 10pm, Thu 8am to 10pm_
> **Parses as**
> _Mon, Tue, Sun 09:00-22:00
> Wed, Thu 08:00-22:00_

> _Sun 9am to 10pm, Mon 9am to 10pm, Tue 8am to 10pm, Wed 9am to 10pm, Thu 8am to 10pm_
> **Parses as**
> _Mon, Wed, Sun 09:00-22:00
> Tue, Thu 08:00-22:00_

And it does not matter where the Sunday/Monday is located.  Just that they are the same hours and no other day is the same hours
> _Mon 9am to 10pm, Tue 8am to 10pm, **Sun 9am to 10pm**, Wed 8am to 10pm, Thu 8am to 10pm_
> **Parses as** 
> _Mon 09:00-22:00
> Tue- Thu 08:00-22:00_

> _Mon 9am to 10pm, Tue 8am to 10pm, **Sun 9am to 10pm**, Wed 8am to 10pm, Thu 9am to 10pm_
> **Parses as**
> _Mon, Thu, Sun 09:00-22:00_
> _Tue, Wed 08:00-22:00_

**Comment by mapomatic** [comment]
Thanks.  This _should_ be fixed with the latest version of the HoursParser library, which will propagate to WMEPH beta, WMEPH prod, and PIE in one of two ways:
1) when those scripts receive a new update
2) when TM checks for new externals, which is a user-dependent setting (If set to "Never", then it will only update when #1 occurs)
