### ISSUE TITLE
Make Tesla station type clickable

### ISSUE THREAD

**Issue by jm6087** [WazeDev/WME-Place-Harmonizer#426]
It would be nice if you could click on "Tesla Supercharger" or "Tesla Destination Charger" and it would update the name field to "Tesla Supercharger - " or "Tesla Destination Charger - "

![image](https://user-images.githubusercontent.com/24948653/226491897-065304f8-3d73-497c-84a1-aa7d6c2ccb15.png)

**Comment by mapomatic** [comment]
It would be.  It sure would.  ;)

**Comment by mapomatic** [comment]
We're working on a longer term solution that should help with this and other scenarios where we need flexibility to add UI elements to messages, but for now I've added a temporary solution for the Tesla thing.
