### ISSUE TITLE
Parking Lot checks & more info tab (PLEASE DISCUSS!)

### ISSUE THREAD

**Issue by t0cableguy** [WazeDev/WME-Place-Harmonizer#62]
COST=null blue severity. note "No Cost selected. Please select a Cost for this lot."
if cost is selected
COST=Free uncheck cc cash checks payment types and POSSIBLY disable them.
COST=anything but free, at least one payment type should be checked, if not show warning of yellow (or blue if required to allow automatic lock), allow automatic locking, and show a note (or something shorter...): "No type of payment selected, but payment is required. Please select a payment type in the More Info tab" 

Create banner buttons for each of the Services for a place and allow them to be automatically turned on for an operator.

Ask if disability parking is available if not already turned on. This should almost always be checked ON in USA. Note: "Is disablity parking available here?" buttons for Yes/No. Yes turns service on. No = whitelist for disability.

Lot Type
At least one type checked. or lot should be red (prevent locking) and display note: At least one lot type is required.

**Comment by jm6087** [comment]
Looks good to me.  Maybe even give the option of default checking disability in US

**Comment by PesachZ** [comment]
I think it looks great, though I don't like the idea of defaulting to disabled on. There are definitely lots with no handicapped spots especially smaller lots

**Comment by t0cableguy** [comment]
This is why I suggested a Yes/No for disablity parking.. There are a few that don't have it, but they will be far and few between.

**Comment by mapomatic** [comment]
I believe all of these things have been addressed.
