### ISSUE TITLE
Refactor - Put LZ compression code in separate file and @require

### ISSUE THREAD

**Issue by mapomatic** [WazeDev/WME-Place-Harmonizer#76]

**Comment by mapomatic** [comment]
Regarding the discussion whether or not it made sense to just remove the compression completely, this article may help in that decision:

https://www.html5rocks.com/en/tutorials/offline/quota-research/

**Comment by t0cableguy** [comment]
So with that in mind, seems like 10mb is a pretty low amount of space to share with every script in waze. Possibly it is more important for things to be compressed than we assumed?

**Comment by RavenDT** [comment]
Good find, Mike.

This is definitely something we need to invest time and research into
before choosing a solution.

**Comment by mapomatic** [comment]
I've removed the lzstring code from the script, and @required it.  Closing this issue.
