### ISSUE TITLE
Idea - process multiple input boxes

### ISSUE THREAD

**Issue by helifino** [WazeDev/WME-Place-Harmonizer#80]
Some fools (me) have a tendency to fill in multiple boxes at once before hitting an 'Add' button. It would be wonderous if the script checked for a nonempty state on the other boxes and did the appropriate thing if multiple boxes were filled in.

**Comment by StormeHawke** [comment]
Yes!

**Comment by StormeHawke** [comment]
Or at the very least, don't clear the other boxes

**Comment by mapomatic** [comment]
I've been meaning to look into doing this for a long time.  Maybe it's time to do something about it :)

**Comment by mapomatic** [comment]
Fixed (I hope...)
