### ISSUE TITLE
Remove parent categories when matching to PNH

### ISSUE THREAD

**Issue by t0cableguy** [WazeDev/WME-Place-Harmonizer#84]
If a category is added from pnh that is not a "parent" category, the parent category should be removed. IE fashion & clothing should remove shopping and services, unless the pnh sheet is set to include shopping and services also.

in short, Parent categories should go away if a non parent category is pulled from the pnh sheet. 
ie lodging, shopping and services, professional and public etc.

Other categories that are not parent categories should stay.

**Comment by helifino** [comment]
Also, categories should not be stripped if suggested as possible by PNH.

**Comment by mapomatic** [comment]
This was completed for PNH-matched places.
